In [1]:
import pandas as pd

In [10]:
pwd

'/Users/tedu/Workspace/DCP/EDM/embedding/EDDT/db-equitable-development-tool/notebooks'

In [2]:
df = pd.read_csv('/Users/tedu/Workspace/DCP/EDM/embedding/EDDT/db-equitable-development-tool/data/HVS_data_2017.csv')

df.head()

,recid,boro,uf1_1,uf1_3,uf1_4,uf1_5,uf1_6,uf1_7,uf1_8,uf1_9,...,fw74,fw75,fw76,fw77,fw78,fw79,fw80,il30per,il50per,il80per
0,1,1,9,9,9,1,9,9,9,9,...,37635401,33263895,10348898,11446240,32161257,9745805,13739972,21800,36250,58000
1,1,1,9,9,9,1,9,9,9,9,...,8270628,23614216,42797335,19594333,8525261,36330659,28940264,27200,45300,72500
2,1,1,9,9,9,1,9,9,9,9,...,8270628,23614216,42797335,19594333,8525261,36330659,28940264,24500,40800,65250
3,1,1,9,9,9,1,9,9,9,9,...,35934838,10027288,46175949,57167298,43401081,10664017,66729558,21800,36250,58000
4,1,1,9,9,9,1,9,9,9,9,...,50290497,10630692,32310018,70148673,42706530,10137630,64932695,21800,36250,58000

In [3]:
df.columns

Index(['recid', 'boro', 'uf1_1', 'uf1_3', 'uf1_4', 'uf1_5', 'uf1_6', 'uf1_7',
       'uf1_8', 'uf1_9',
       ...
       'fw74', 'fw75', 'fw76', 'fw77', 'fw78', 'fw79', 'fw80', 'il30per',
       'il50per', 'il80per'],
      dtype='object', length=269)

In [5]:
# this this income to rent ratio 
df['uf30']

0        9999
1           0
2         609
3           0
4        9999
         ...
13261     241
13262    9999
13263    9999
13264     359
13265     238
Name: uf30, Length: 13266, dtype: int64

In [8]:
df.loc[df['uf2a_1'] != 1]

,recid,boro,uf1_1,uf1_3,uf1_4,uf1_5,uf1_6,uf1_7,uf1_8,uf1_9,...,fw74,fw75,fw76,fw77,fw78,fw79,fw80,il30per,il50per,il80per
9,1,1,9,9,9,1,9,9,9,9,...,38915519,26093538,21804499,26345496,6557403,29329330,39833848,27200,45300,72500
15,1,1,9,9,9,1,9,9,9,9,...,47718577,22894405,43854983,32979398,48088603,37602300,27029150,99999,99999,99999
43,1,1,9,9,9,1,9,9,9,9,...,8567108,55001538,26893499,27384062,26237974,27917450,29326379,19050,31750,50750
46,1,1,9,9,9,1,9,9,9,9,...,6149349,30101129,22864088,16953145,22189200,19120187,20976775,19050,31750,50750
67,1,1,9,9,9,1,9,9,9,9,...,6491768,18710478,23524720,19783820,36716761,20001013,6117123,19050,31750,50750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12746,1,5,9,9,9,1,9,9,9,9,...,20429759,7339042,33916451,6417528,31061835,6098121,35216872,40890,59800,95700
12928,1,5,9,9,9,1,9,9,9,9,...,25853022,18930601,4442625,28361715,15326122,17118502,15350726,27200,45300,72500
12952,1,5,9,9,9,1,9,9,9,9,...,7006149,23228845,29829129,36942524,24974872,6705740,24628128,21800,36250,58000
13175,1,5,9,9,9,1,9,9,9,9,...,42536719,21982170,7943881,23994317,24320665,26977432,39267060,27200,45300,72500
13231,1,5,9,9,9,1,9,9,9,9,...,23124915,26023664,6991489,28044213,48217770,22542177,26013154,21800,36250,58000

In [12]:
import pandas as pd
from pandas.core.reshape.pivot import crosstab
from ingest.load_data import load_HVS
#from aggregate.race_assign import HVS_race_assign
#from statistical.calculate_counts import calculate_counts
#from aggregate.clean_aggregated import sort_columns
#from ingest.clean_replicate_weights import rw_cols_clean
#from internal_review.set_internal_review_file import set_internal_review_files

In [11]:
import sys
sys.path.append('../utils')
import wd_management
wd_management.set_wd_root()

called set_wd_root. current working directory is /Users/tedu/Workspace/DCP/EDM/embedding/EDDT/db-equitable-development-tool/notebooks

In [14]:
HVS = load_HVS(requery=False, year=2017, human_readable=True)

In [15]:
HVS.head()

,Record Type,Borough,External Walls--Missing brick and sloping walls,External Walls--Major cracks in walls,External Walls--Loose or hanging cornice,External Walls--No problems,External Walls--Unable to observe,Condition of Windows--Broken/missing,Condition of Windows--Rotten/loose,Condition of Windows--Boarded-up,...,Replicate Weight #74,Replicate Weight #75,Replicate Weight #76,Replicate Weight #77,Replicate Weight #78,Replicate Weight #79,Replicate Weight #80,30% HUD Income Limits,50% HUD Income Limits,80% HUD Income Limits
0,1,1,9,9,9,1,9,9,9,9,...,37635401,33263895,10348898,11446240,32161257,9745805,13739972,21800,36250,58000
1,1,1,9,9,9,1,9,9,9,9,...,8270628,23614216,42797335,19594333,8525261,36330659,28940264,27200,45300,72500
2,1,1,9,9,9,1,9,9,9,9,...,8270628,23614216,42797335,19594333,8525261,36330659,28940264,24500,40800,65250
3,1,1,9,9,9,1,9,9,9,9,...,35934838,10027288,46175949,57167298,43401081,10664017,66729558,21800,36250,58000
4,1,1,9,9,9,1,9,9,9,9,...,50290497,10630692,32310018,70148673,42706530,10137630,64932695,21800,36250,58000

In [23]:
HVS['Total persons recode'].head()

0    2
1    4
2    3
3    2
4    2
Name: Total persons recode, dtype: int64

In [24]:
HVS['Household weight']

0        34040517
1        24577110
2        24577110
3        37098358
4        37041707
           ...
13261      475251
13262      473395
13263      530555
13264      526384
13265      475251
Name: Household weight, Length: 13266, dtype: int64

In [21]:
print(HVS.columns.to_list())

['Record Type', 'Borough', 'External Walls--Missing brick and sloping walls', 'External Walls--Major cracks in walls', 'External Walls--Loose or hanging cornice', 'External Walls--No problems', 'External Walls--Unable to observe', 'Condition of Windows--Broken/missing', 'Condition of Windows--Rotten/loose', 'Condition of Windows--Boarded-up', 'Condition of Windows--No problems', 'Condition of Windows--Unable to observe', 'Condition of Stairways--Loose/broken railings', 'Condition of Stairways--Loose/broken steps', 'Condition of Stairways--No problems', 'Condition of Stairways--No interior steps', 'Condition of Stairways--No exterior steps', 'Condition of Stairways--Unable to observe', 'Condition of Floors--Sagging/sloping and slanted doors', 'Condition of Floors--Deep wear', 'Condition of Floors--Holes/missing flooring', 'Condition of Floors--None of these problems', 'Condition of Floors--Unable to observe', 'Condition of building', 'Broken/Boarded Windows--observation', 'Wheelchair accessibility--Street entry', 'Wheelchair accessibility--Elevator', 'Wheelchair accessibility--Unit entrance', 'Sex of householder', 'Age of householder', 'Hispanic origin', 'Race of householder', 'Number of persons from temporary residence', 'Most recent place lived', 'Year Householder Moved into Unit Recode', 'First occupants of unit', 'Reason for moving', 'Place of birth-householder', 'Place of birth-father', 'Place of birth-mother', 'Coop/condo status', 'Tenure(1)', 'Tenure(2)', 'Lived in unit at time of coop/condo conversion', 'Coop/condo conv. through a non-eviction plan', 'Occupancy status before acquisition', 'Condo/Coop before acquisition', 'Down payment(1)', 'Down payment(2)', 'Value', 'Mortgage status', 'When Did Most Recent Mortgage Originate', 'Current Interest Rate', 'Fire and liability insurance paid separately', 'Real estate taxes paid separately', 'Units in building', 'Owner in building', 'Stories in building', 'Elevator in building', 'Sidewalk to elevator', 'Sidewalk to unit', 'Number of rooms', 'Number of bedrooms', 'Complete plumbing facilities', 'Toilet breakdown', 'Complete kitchen facilities', 'Kitchen facilities functioning', 'Type of heating fuel', 'Electricity-paid separately', 'Monthly electricity cost', 'Gas-paid separately', 'Monthly gas cost', 'Combined gas/electricity', 'Water and sewer-paid separately', 'Yearly water and sewer cost', 'Other fuels-paid separately', 'Yearly cost for other fuels', 'Contract rent', 'Length of lease', 'Federal section 8', 'Other rental subsidy', 'Out of pocket rent', 'Heating equipment breakdown', 'Number of heating breakdowns', 'Functioning Air Conditioning', 'Additional sources of heat', 'Presence of mice and rates', 'Number of Cockroaches', 'Exterminator service', 'Cracks/holes in interior walls', 'Holes in floors', 'Broken plaster/peeling paint', 'Plaster/paint> 8.5 x 11', 'Water leakage', 'Respondent rating of structures in neighborhood', 'Receipt of public assistance or welfare payments', 'Land-line Telephone in House', 'Number of Adults with a cell phone', 'General Health (respondent)', 'Medical device in home', 'Dental', 'Preventative care/check-up', 'Mental health', 'Treatment or diagnosis of illness', 'Prescription drugs', 'One or more utility', 'Landline telephone', 'Cell phone', 'Cable/internet', 'Other', 'Affordable', 'Too expensive given its condition', 'Too expensive given its location', 'Moved to the US as immigrant', 'Year moved to US as immigrant', 'Year moved to NYC', 'New control status recode', 'Structure class recode', 'Type of schedule code', 'Year built recode', 'Condition of unit recode', 'Respondent line number', 'Household composition recode', 'Presence of nonrelatives', 'Race and Ethnicity of householder', 'Race Recode 1', 'Monthly owner cost recode', 'Number of 1987 maintenance deficiencies', 'Number of 2017 maintenance deficiencies', 'Total persons recode', 'Persons per room', 'Monthly gross rent', 'Monthly gross rent per room recode', 'Monthly contract rent per room recode', 'Household below poverty', 'Household income recode', 'Household income flag', 'Salary', 'Salary flag', 'Business income', 'Business income flag', 'Interest income', 'Interest income flag', 'Retirement income (1)', 'Retirement income (1) flag', 'Retirement income (2)', 'Retirement income (2) flag', 'Government income', 'Government income flag', 'Other income', 'Other income flag', 'Sub-borough area', 'Gross rent/income ratio', 'Contract rent/income ratio', 'Household members under 6', 'Household members under 18', 'Household weight', 'Final household weight', 'Sequence number', 'Sex of householder.1', 'Age of householder.1', 'Hispanic Origin', 'Race of householder.1', 'Year moved in flag', 'Year acquired flag', 'Value flag', 'Stories in building flag', 'Rooms/Bedrooms flag', 'Plumbing facilities flag', 'Kitchen facilities flag', 'Type of heating fuel flag', 'Electricity cost flag', 'Gas cost flag', 'Combined gas/electricity cost flag', 'Water and sewer cost flag', 'Other fuels cost flag', 'Contract rent flag', 'Rental assistance flag', 'Household income flag.1', 'Salary income flag', 'Business income flag.1', 'Interest income flag.1', 'Retirement income(1) flag', 'Government income flag.1', 'Retirement income(2) flag', 'Other income flag.1', 'Replicate Weight #1', 'Replicate Weight #2', 'Replicate Weight #3', 'Replicate Weight #4', 'Replicate Weight #5', 'Replicate Weight #6', 'Replicate Weight #7', 'Replicate Weight #8', 'Replicate Weight #9', 'Replicate Weight #10', 'Replicate Weight #11', 'Replicate Weight #12', 'Replicate Weight #13', 'Replicate Weight #14', 'Replicate Weight #15', 'Replicate Weight #16', 'Replicate Weight #17', 'Replicate Weight #18', 'Replicate Weight #19', 'Replicate Weight #20', 'Replicate Weight #21', 'Replicate Weight #22', 'Replicate Weight #23', 'Replicate Weight #24', 'Replicate Weight #25', 'Replicate Weight #26', 'Replicate Weight #27', 'Replicate Weight #28', 'Replicate Weight #29', 'Replicate Weight #30', 'Replicate Weight #31', 'Replicate Weight #32', 'Replicate Weight #33', 'Replicate Weight #34', 'Replicate Weight #35', 'Replicate Weight #36', 'Replicate Weight #37', 'Replicate Weight #38', 'Replicate Weight #39', 'Replicate Weight #40', 'Replicate Weight #41', 'Replicate Weight #42', 'Replicate Weight #43', 'Replicate Weight #44', 'Replicate Weight #45', 'Replicate Weight #46', 'Replicate Weight #47', 'Replicate Weight #48', 'Replicate Weight #49', 'Replicate Weight #50', 'Replicate Weight #51', 'Replicate Weight #52', 'Replicate Weight #53', 'Replicate Weight #54', 'Replicate Weight #55', 'Replicate Weight #56', 'Replicate Weight #57', 'Replicate Weight #58', 'Replicate Weight #59', 'Replicate Weight #60', 'Replicate Weight #61', 'Replicate Weight #62', 'Replicate Weight #63', 'Replicate Weight #64', 'Replicate Weight #65', 'Replicate Weight #66', 'Replicate Weight #67', 'Replicate Weight #68', 'Replicate Weight #69', 'Replicate Weight #70', 'Replicate Weight #71', 'Replicate Weight #72', 'Replicate Weight #73', 'Replicate Weight #74', 'Replicate Weight #75', 'Replicate Weight #76', 'Replicate Weight #77', 'Replicate Weight #78', 'Replicate Weight #79', 'Replicate Weight #80', '30% HUD Income Limits', '50% HUD Income Limits', '80% HUD Income Limits']